// 각 페이지 SEO 차별화 설정. 키워드 스터핑 없는 후킹 카피.
// title 25-70, description 60-165 chars. 키워드는 자연어 흐름 유지.

const SITE = {
  baseUrl: 'https://ulsan2.pages.dev',
  siteName: '울산챔피언나이트 춘자',
  phone: '010-5653-0069',
  kakao: 'besta12',
  ogDefault: 'https://ulsan2.pages.dev/og-images/main.png',
  modifiedDate: '2026-05-26',
};

// 헤더 바 브랜드 — 페이지별로 미묘하게 다르게 (스터핑 방지)
// 페이지마다 "울산챔피언나이트" 단어 카운트를 의도적으로 분산
const PAGES = {
  home: {
    path: 'index.html',
    type: 'home',
    title: '울산챔피언나이트 후기 11선 — 직접 가본 놈만 쓴 리얼 체험기',
    description: '울산챔피언나이트 진짜 어떤지 궁금해? 첫 방문·혼자·커플·40대까지 직접 가본 10명이 솔직하게 썼다. 안 보면 후회한다.',
    keywords: '울산챔피언나이트,울산챔피언나이트 춘자,울산 나이트,울산 나이트클럽,챔피언나이트 후기,울산 클럽,울산 밤문화,울산 놀거리,울산 챔피언,울산 나이트 추천',
    h1: '울산챔피언나이트', // 홈은 브랜드가 H1
    headerBrand: '울산챔피언나이트',
    headerSub: '리얼 후기 · 체험기 · 꿀팁 블로그',
    ogImage: 'https://ulsan2.pages.dev/og-images/main.png',
    ogImageAlt: '울산챔피언나이트 춘자 — 울산 대표 나이트클럽',
    hookH2: '솔직히 말해서.<br>직접 가보고 쓴 글만 모았다.<br><em>읽고 판단은 니가 해.</em>',
    section: '메인',
    footerBrand: '챔피언 블로그',
  },
  'first-time': {
    path: 'blog/first-time/index.html',
    type: 'article',
    h1: '문 열고 3초 — 처음이라 떨렸던 그날 밤 솔직 후기',
    title: '처음이라 떨렸다 — 문 열고 3초 만에 알아버린 것 | 울산챔피언나이트',
    description: '울산챔피언나이트 처음 가는데 겁났다. 근데 문 여는 순간 알았다. 베이스 진동, 조명, 첫 하이볼까지 — 그날 밤 10분 안에 일어난 일.',
    keywords: '울산챔피언나이트 첫방문,울산챔피언나이트 후기,처음 가는 나이트,울산 나이트 입장,울산 나이트클럽 첫방문,챔피언나이트 드레스코드,울산 나이트 처음',
    headerBrand: '챔피언 후기',
    headerSub: '처음 가는 사람을 위한 가이드',
    ogImageAlt: '문 열고 3초 — 첫 방문 후기',
    section: '첫 방문 후기',
    publishedAt: '2026-03-24',
    seriesNum: 1,
    nextUrl: '/blog/weekend/',
    nextTitle: '금토 비교',
    nextBarLabel: '금요일 vs 토요일 비교',
    achieveEmoji: '🎉',
    achieveTitle: '첫 방문 후기 완독!',
    achieveBody: '이제 주말 비교 글도 읽어볼까?',
    faq: [
      ['처음 가도 어색하지 않나요?', '문 열고 10분이면 적응됩니다. 베이스 진동·조명·사운드가 분위기를 만들어줘서 어색할 틈이 없습니다.'],
      ['옷차림은 뭐가 좋아요?', '깔끔하기만 하면 됩니다. 검정 셔츠에 슬랙스 정도, 운동화도 괜찮습니다. 너무 후줄근만 피하세요.'],
      ['입장료는 얼마인가요?', '시즌·요일에 따라 다릅니다. 정확한 금액은 010-5653-0069로 문의하시면 빠릅니다.'],
    ],
    related: [
      ['/blog/weekend/', '금요일과 토요일, 분위기가 왜 다른지'],
      ['/blog/alone/', '혼자 갔다가 오히려 더 편했던 이야기'],
      ['/blog/safety/', '실수 안 하려면 미리 알아둘 것들'],
    ],
  },
  weekend: {
    path: 'blog/weekend/index.html',
    type: 'article',
    h1: '간판은 같다 — 안에 들어가면 딴 세상인 금토 비교',
    title: '같은 곳인데 분위기가 왜 다르냐면 — 금요일 vs 토요일 비교',
    description: '금요일은 하이볼 마시며 녹는 라운지 분위기. 토요일은 땀 흘리며 미치는 플로어. 두 번 다 직접 가본 사람이 정리한 진짜 차이.',
    keywords: '금요일 토요일 비교,주말 나이트 후기,울산 주말 놀거리,금요일 나이트 분위기,토요일 나이트 분위기,챔피언 금토,주말 클럽 추천',
    headerBrand: '금토 비교',
    headerSub: '같은 곳, 다른 두 밤',
    ogImageAlt: '금요일과 토요일 — 같은 곳 다른 분위기',
    section: '주말 비교 후기',
    publishedAt: '2026-03-25',
    seriesNum: 2,
    nextUrl: '/blog/over40/',
    nextTitle: '40대 후기',
    nextBarLabel: '40대도 즐긴다',
    achieveEmoji: '📅',
    achieveTitle: '주말 비교 완독!',
    achieveBody: '금토 차이 이제 알겠지?',
    faq: [
      ['금요일이랑 토요일 뭐가 달라요?', '금요일은 라운지 느낌, 대화도 되고 술도 천천히 마실 수 있어요. 토요일은 쉴 틈 없이 몰아치는 플로어입니다.'],
      ['언제 가는 게 베스트인가요?', '금요일은 11시~새벽 1시, 토요일은 11시 반~12시가 피크입니다. 토요일은 10시 반에 가면 줄 안 섭니다.'],
    ],
    related: [
      ['/blog/first-time/', '처음 가는 사람을 위한 가이드'],
      ['/blog/event/', '이벤트 날의 미친 분위기'],
      ['/blog/couple/', '여자친구랑 갔던 데이트 후기'],
    ],
  },
  over40: {
    path: 'blog/over40/index.html',
    type: 'article',
    h1: '40대가 가봤다 — 20대보다 잘 놀았다는 솔직한 이야기',
    title: '40대가 갔더니 20대보다 잘 놀더라 | 진짜 후기',
    description: '"이 나이에 거기를?" 했던 사람이 40대 친구 셋과 다녀온 밤. 무릎은 아팠는데 다음 주에 또 갔다. 40·50대도 충분히 즐기는 이유.',
    keywords: '40대 나이트 후기,40대 클럽,40대 놀거리,40대 밤문화,울산 40대 추천,40대 50대 클럽,중장년 나이트',
    headerBrand: '40대 후기',
    headerSub: '나이는 숫자라더라',
    ogImageAlt: '40대가 가본 밤 — 20대보다 더 잘 놀았다',
    section: '40대 방문 후기',
    publishedAt: '2026-03-26',
    seriesNum: 3,
    nextUrl: '/blog/couple/',
    nextTitle: '커플 후기',
    nextBarLabel: '커플 데이트 후기',
    achieveEmoji: '🍷',
    achieveTitle: '40대 후기 완독!',
    achieveBody: '나이는 숫자라는 거 이제 알겠지?',
    faq: [
      ['40대도 가도 어색하지 않나요?', '오히려 40·50대가 더 여유롭게 즐깁니다. 음악 취향(2000년대 히트곡)도 자주 나와서 분위기 잘 맞습니다.'],
      ['체력이 걱정인데요', '바 자리에 앉아 천천히 즐겨도 됩니다. 풀로 달리는 건 무리, 2-3시간 적당히 머무는 게 베스트입니다.'],
    ],
    related: [
      ['/blog/first-time/', '처음 가는 사람을 위한 가이드'],
      ['/blog/food/', '술 잘 마시려면 미리 먹어야 할 코스'],
      ['/blog/safety/', '실수 안 하려면 미리 알아둘 것들'],
    ],
  },
  couple: {
    path: 'blog/couple/index.html',
    type: 'article',
    h1: '여친 데려갔다 — "또 가자" 소리 들었던 그날 데이트',
    title: '여자친구가 "역대급 데이트"라고 한 이유 | 커플 후기',
    description: '"거기 같이 가자" 말 꺼냈을 때 여친 3초 침묵. 근데 나오면서 한 말이 "또 가자"였다. 커플로 가는 게 의외로 괜찮은 진짜 이유.',
    keywords: '커플 데이트 코스,클럽 데이트,울산 커플 놀거리,여친 데이트,커플 클럽 후기,울산 데이트 추천,주말 데이트',
    headerBrand: '커플 후기',
    headerSub: '둘이 가서 더 좋았던 밤',
    ogImageAlt: '커플 데이트 — 둘이 갔던 그날 밤',
    section: '커플 방문 후기',
    publishedAt: '2026-03-27',
    seriesNum: 4,
    nextUrl: '/blog/alone/',
    nextTitle: '혼자 후기',
    nextBarLabel: '혼자 갔던 솔직 후기',
    achieveEmoji: '💑',
    achieveTitle: '커플 후기 완독!',
    achieveBody: '데이트 코스로 추천해봐!',
    faq: [
      ['여자친구랑 같이 가도 괜찮나요?', '오히려 커플 데이트로 인기입니다. 라운지 자리도 있고 분위기 좋아서 데이트 코스로 자주 활용됩니다.'],
      ['몇 시쯤 가는 게 좋아요?', '커플은 10시~12시 추천. 너무 늦으면 사람이 많아 대화가 어렵습니다.'],
    ],
    related: [
      ['/blog/weekend/', '금요일과 토요일 분위기 비교'],
      ['/blog/food/', '데이트 전 추천 맛집 코스'],
      ['/blog/event/', '이벤트 데이가 더 특별한 이유'],
    ],
  },
  alone: {
    path: 'blog/alone/index.html',
    type: 'article',
    h1: '혼자 간 놈의 고백 — 오히려 더 자유로웠다',
    title: '혼자 가도 되냐고? 가본 사람이 답한다 | 솔로 방문기',
    description: '현관문 앞에서 10분 멈췄다. 혼자 거기를 가는 게 말이 되나? 근데 가보니 그게 더 편했다. 솔로로 가는 사람을 위한 진짜 가이드.',
    keywords: '혼자 클럽,혼자 나이트,솔로 놀거리,혼자 놀기,울산 혼술,혼자 나이트 후기,1인 클럽,솔로 밤문화',
    headerBrand: '솔로 후기',
    headerSub: '혼자라서 더 자유로웠다',
    ogImageAlt: '혼자 가본 밤 — 오히려 더 편했다',
    section: '솔로 방문 후기',
    publishedAt: '2026-03-28',
    seriesNum: 5,
    nextUrl: '/blog/summer/',
    nextTitle: '여름밤 체험',
    nextBarLabel: '여름밤 바다에서 플로어까지',
    achieveEmoji: '🍸',
    achieveTitle: '혼자 방문기 완독!',
    achieveBody: '용기 내서 한번 가봐!',
    faq: [
      ['혼자 가도 어색하지 않나요?', '바에 혼자 앉아 있는 사람이 의외로 많습니다. 자연스럽게 새로운 사람을 만나기도 좋습니다.'],
      ['혼자 가서 뭐 해요?', '바 카운터에서 분위기 파악 → 댄스플로어에서 자유롭게 즐기면 됩니다. 누구 눈치 볼 일 없습니다.'],
    ],
    related: [
      ['/blog/first-time/', '처음 가는 사람을 위한 가이드'],
      ['/blog/safety/', '혼자 갈 때 알아둘 안전 수칙'],
      ['/blog/food/', '혼술 전 미리 먹을 코스'],
    ],
  },
  summer: {
    path: 'blog/summer/index.html',
    type: 'article',
    h1: '바다에서 플로어까지 — 여름밤 풀코스 후기',
    title: '낮엔 바다, 밤엔 댄스플로어 | 울산 여름밤 풀코스',
    description: '낮에 일산해수욕장, 저녁에 회 한 접시, 밤에 에어컨 바람 맞으며 모히토. 여름 울산을 통째로 즐긴 24시간 풀코스 후기.',
    keywords: '울산 여름밤,일산해수욕장,울산 여름 놀거리,여름 클럽,울산 바캉스,여름 모히토,울산 여름 데이트',
    headerBrand: '여름밤 후기',
    headerSub: '바다 → 회 → 플로어',
    ogImageAlt: '여름밤 — 바다부터 댄스플로어까지',
    section: '여름 방문 후기',
    publishedAt: '2026-03-29',
    seriesNum: 6,
    nextUrl: '/blog/event/',
    nextTitle: '이벤트 후기',
    nextBarLabel: '이벤트 날 미친 분위기',
    achieveEmoji: '🌊',
    achieveTitle: '여름밤 후기 완독!',
    achieveBody: '이번 여름 풀코스 짜봐!',
    faq: [
      ['여름에 가도 더위 안 타나요?', '에어컨이 강하게 가동되고, 입장하면 시원합니다. 모히토 한 잔이면 더위는 잊어버립니다.'],
      ['낮부터 가는 코스 추천?', '오전 해수욕장 → 점심 회 → 저녁 카페 → 밤 라운지 → 새벽 국밥 순이 베스트입니다.'],
    ],
    related: [
      ['/blog/food/', '여름 추천 맛집 코스'],
      ['/blog/weekend/', '주말 분위기 비교'],
      ['/blog/event/', '여름 시즌 이벤트 정보'],
    ],
  },
  event: {
    path: 'blog/event/index.html',
    type: 'article',
    h1: '조명 꺼지고 5초 — 이벤트 날에만 일어나는 일',
    title: '한 달에 두 번 — 이벤트 날의 미친 분위기 | 후기',
    description: '한 달에 두세 번 열리는 이벤트 데이. 레드카펫·게스트 DJ·천장에서 떨어지는 풍선까지. 평소엔 못 보는 것만 모은 후기.',
    keywords: '이벤트 데이,게스트 DJ,클럽 이벤트,파티 후기,울산 이벤트,EDM 파티,스페셜 데이',
    headerBrand: '이벤트 후기',
    headerSub: '평소엔 못 보는 밤',
    ogImageAlt: '이벤트 데이 — 평소엔 못 보는 광경',
    section: '이벤트 방문 후기',
    publishedAt: '2026-03-30',
    seriesNum: 7,
    nextUrl: '/blog/vs/',
    nextTitle: '나이트 비교',
    nextBarLabel: '3년 다닌 놈의 비교',
    achieveEmoji: '🎆',
    achieveTitle: '이벤트 후기 완독!',
    achieveBody: '다음 이벤트 놓치지마!',
    faq: [
      ['이벤트는 얼마나 자주 열리나요?', '한 달에 2-3번 정도. 매주 금토에 작은 이벤트, 한 달에 한 번 대형 이벤트가 있습니다.'],
      ['이벤트 정보는 어디서 보나요?', '카카오톡(besta12) 또는 010-5653-0069로 문의하면 최신 일정 알 수 있습니다.'],
    ],
    related: [
      ['/blog/weekend/', '평일과 이벤트 데이 분위기 차이'],
      ['/blog/summer/', '여름 시즌 특별 이벤트'],
      ['/blog/couple/', '데이트로 즐기는 이벤트 데이'],
    ],
  },
  vs: {
    path: 'blog/vs/index.html',
    type: 'article',
    h1: '3년 다닌 놈의 비교 — A·B·C 다 가본 결론',
    title: '울산 나이트 3년 다닌 후기 — 비교한 결론은 딱 하나 | 솔직 리뷰',
    description: '울산 나이트클럽 A·B·C 다 다녀본 사람이 솔직하게 정리. 음악·공간·가격·분위기 비교한 결과 가장 자주 가게 된 곳의 이유.',
    keywords: '울산 나이트 비교,울산 클럽 비교,나이트 추천,울산 클럽 추천,울산 밤문화 비교,울산 나이트 어디,클럽 리뷰',
    headerBrand: '비교 리뷰',
    headerSub: '3년치 비교 데이터',
    ogImageAlt: '나이트 3곳 비교 — 결론은 하나',
    section: '비교 후기',
    publishedAt: '2026-03-31',
    seriesNum: 8,
    nextUrl: '/blog/food/',
    nextTitle: '맛집 코스',
    nextBarLabel: '술 마시기 전 맛집 코스',
    achieveEmoji: '🏆',
    achieveTitle: '비교 후기 완독!',
    achieveBody: '이제 어디 갈지 고민 끝!',
    faq: [
      ['왜 이 곳을 가장 자주 가나요?', '음향이 가장 좋고, 공간 여유가 있어 답답하지 않습니다. DJ 셀렉트 폭도 가장 넓다고 느꼈습니다.'],
      ['가격대는 어떤가요?', '서울 클럽 대비 80% 수준. 하이볼 기준 가성비 좋습니다.'],
    ],
    related: [
      ['/blog/first-time/', '처음 가는 사람을 위한 가이드'],
      ['/blog/over40/', '40대 후기로 본 분위기'],
      ['/blog/event/', '이벤트 데이가 더 특별한 이유'],
    ],
  },
  food: {
    path: 'blog/food/index.html',
    type: 'article',
    h1: '삼겹살 → 플로어 → 새벽 국밥 — 안 망하는 코스',
    title: '술 마시기 전엔 무조건 먹어둬 | 맛집 풀코스 가이드',
    description: '빈속에 술 마시면 20분 안에 리타이어. 고기로 위벽 코팅 → 놀기 → 새벽 국밥으로 마무리. 실패 없는 풀코스 동선 정리.',
    keywords: '울산 맛집,새벽 국밥,삼겹살,클럽 전 맛집,울산 야식,술 코스,울산 야식 추천',
    headerBrand: '맛집 코스',
    headerSub: '먹고 → 놀고 → 또 먹고',
    ogImageAlt: '맛집 풀코스 — 삼겹살부터 새벽 국밥까지',
    section: '맛집 코스 후기',
    publishedAt: '2026-04-01',
    seriesNum: 9,
    nextUrl: '/blog/safety/',
    nextTitle: '안전 가이드',
    nextBarLabel: '안전하게 노는 법',
    achieveEmoji: '🍜',
    achieveTitle: '맛집 코스 완독!',
    achieveBody: '오늘 밤 코스 짜봐!',
    faq: [
      ['술 마시기 전에 뭐 먹는 게 좋아요?', '기름진 음식이 베스트. 삼겹살·곱창처럼 지방 있는 음식이 위벽을 코팅해줍니다.'],
      ['새벽에 갈 만한 곳은요?', '24시간 국밥집 추천. 해장하면서 다음 날 컨디션 살리기 좋습니다.'],
    ],
    related: [
      ['/blog/safety/', '안 망하려면 알아둘 수칙'],
      ['/blog/couple/', '데이트 코스로 활용하기'],
      ['/blog/summer/', '여름 한정 추천 메뉴'],
    ],
  },
  safety: {
    path: 'blog/safety/index.html',
    type: 'article',
    h1: '실수 다 해본 놈이 쓴다 — 안 망하는 안전 가이드',
    title: '핸드폰 잃어버리고, 필름 끊겨봤다 | 안전 가이드',
    description: '핸드폰 잃어버리고, 필름 끊기고, 새벽에 걸어가본 사람이 쓴 실전 안전 수칙 10가지. 미리 알면 절대 안 당한다.',
    keywords: '클럽 안전,나이트 안전,술 안전,울산 안전,클럽 매너,안전 가이드,술자리 수칙',
    headerBrand: '안전 가이드',
    headerSub: '실수 다 해본 자의 충고',
    ogImageAlt: '안전 가이드 — 실수 안 하려면',
    section: '안전 가이드',
    publishedAt: '2026-04-02',
    seriesNum: 10,
    nextUrl: '/',
    nextTitle: '메인으로',
    nextBarLabel: '다른 후기 더 보기',
    achieveEmoji: '🛡️',
    achieveTitle: '안전 가이드 완독!',
    achieveBody: '이제 안 망하고 놀 수 있어!',
    faq: [
      ['핸드폰 어디에 둬야 안전한가요?', '안주머니가 베스트. 바지 뒷주머니는 흘리기 쉽고 외투 주머니는 도난 위험이 있습니다.'],
      ['새벽에 어떻게 귀가해야 하나요?', '카카오택시 미리 호출 추천. 음주측정·바가지 피하려면 정식 택시가 안전합니다.'],
    ],
    related: [
      ['/blog/first-time/', '처음 가기 전 체크리스트'],
      ['/blog/food/', '안 취하려면 미리 먹어둘 것'],
      ['/blog/alone/', '혼자 갈 때 더 챙겨야 할 것'],
    ],
  },
};

module.exports = { SITE, PAGES };
